image: maven:3.8.3-jdk-11

variables:
  MAVEN_LOCAL_REPOSITORY: "-Dmaven.repo.local=./.m2/repository"

stages:
  - build
  - build_deploy_nexus

build:
  stage: build
  only:
    - merge_requests
    - cicd
  except:
    - tags
  script:
    - mvn --settings maven-settings.xml clean package
    - ls -la ./impl/target
  artifacts:
    paths:
      - impl/target/*.jar
  cache:
    paths:
      - ./impl/target
      - ./domain/target

build_deploy_nexus:
  stage: build_deploy_nexus
  only:
    - master
    - develop
    - cicd
  except:
    - tags
  script:
    - mvn --settings maven-settings.xml clean deploy
    - ls -la ./impl/target
  artifacts:
    paths:
      - impl/target/*.jar
  cache:
    paths:
      - ./impl/target
      - ./domain/target


