server:
  port: 8080
  error:
    include-message: always

spring:

  boot:
    admin:
      client:
        enabled: true
        instance:
          service-url: http://microservice-person:8080

  liquibase:
    enabled: true
    drop-first: false
    change-log: classpath:database-post-changelog.xml
    default-schema: post

  datasource:
    url: jdbc:${DATABASE_URL:postgresql://localhost:5432/skillbox}
#    url: jdbc:postgresql://localhost:5432/skillbox
#    username: person
    username: ${USER_DB:post-service}
    password: ${PASS_DB:post-service}
    driverClassName: org.postgresql.Driver

  sql:
    init:
      mode: never
      schema-locations: classpath:schema.sql


  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: true
        default_schema: ${SCHEMA_DB:post}
    open-in-view: false

rest:
  password: ${ACCOUNT_SERVICE_PASS:428d34bc-e6ce-499a-9f20-934f554bdd8d}
  account-service-host: ${ACCOUNT_SERVICE_HOST:http://130.61.44.151}



